import { ColumnType, TaskType } from "./types";

export const COLUMNS: ColumnType[] = [
  {
    _id: "col1",
    id: "col1",
    title: "Backlog",
    boardId: "board1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "col2",
    id: "col2",
    title: "In Progress",
    boardId: "board1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "col3",
    id: "col3",
    title: "Done",
    boardId: "board1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_TASKS: TaskType[] = [
  {
    _id: "1",
    id: "1",
    title: "Research Competitors",
    description: "Analyze market trends",
    status: "Backlog",
    boardId: "board1",
    columnId: "col1",
    createdBy: "user1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "2",
    id: "2",
    title: "Design System",
    description: "Create color palette",
    status: "Backlog",
    boardId: "board1",
    columnId: "col1",
    createdBy: "user1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "3",
    id: "3",
    title: "Client Meeting",
    description: "Review initial draft",
    status: "Done",
    boardId: "board1",
    columnId: "col3",
    createdBy: "user1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "4",
    id: "4",
    title: "Database Setup",
    description: "Configure PostgreSQL",
    status: "Backlog",
    boardId: "board1",
    columnId: "col1",
    createdBy: "user1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "5",
    id: "5",
    title: "Auth Flow",
    description: "Implement NextAuth",
    status: "In Progress",
    boardId: "board1",
    columnId: "col2",
    createdBy: "user1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "6",
    id: "6",
    title: "Unit Testing",
    description: "Write tests for API",
    status: "Done",
    boardId: "board1",
    columnId: "col3",
    createdBy: "user1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
